### ISSUE TITLE
Save the CI build in an artifact

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/palm-treee-css#53]
Maybe we should save this in an artifact, so we have the build and can use it to deploy it to a CDN or upload it to NPM. Let's not think about this for now but when we are closer to release 2.0 we can do it.

_Originally posted by @adonyssantos in https://github.com/adonyssantos/palm-tree-css/pull/52#discussion_r1548613757_

**Comment by 0s1n** [comment]
How about we do pair programming so we can solve this issue? Just an idea

**Comment by joer9514** [comment]
@0s1n Let's go !
