### ISSUE TITLE
Fix grid responsive

### ISSUE THREAD

**Issue by 0s1n** [adonyssantos/palm-treee-css#62]
> Still not working. ![imagen](https://private-user-images.githubusercontent.com/95647031/320169420-f26e1a41-bef1-4960-b214-93bc63fbb721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjgyNTksIm5iZiI6MTcxMjM2Nzk1OSwicGF0aCI6Ii85NTY0NzAzMS8zMjAxNjk0MjAtZjI2ZTFhNDEtYmVmMS00OTYwLWIyMTQtOTNiYzYzZmJiNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxNDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWU2YzE3MThkZmQ0MjI5ZjYzMmY3OGU4MGU4MTkyZDRiMmU4ZGVhMWI1ODVkNzdlZDBmNjY5MDhhYjQwYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAeX9t8jgRuxjiBrj3-72f8Ch-kJIGbgF-0DKCB6wWo)

@0s1n Fixed again. There is a error with the grid responsive but we can work this in another issue. 

The problem is that it should show 4 columns on the desktop:  
![image](https://github.com/adonyssantos/palm-tree-css/assets/58638286/72c5687e-5553-497b-9f83-c0fed2c0d45b)

Also, we need to check the horizontal spacing on mobile:
![image](https://github.com/adonyssantos/palm-tree-css/assets/58638286/257fadf4-8a2f-45e2-93f2-c77113978627)

_Originally posted by @adonyssantos in https://github.com/adonyssantos/palm-tree-css/issues/60#issuecomment-2040853572_

**Comment by joer9514** [comment]
@adonyssantos The horizontal space that you mention, corresponds to the scroll

**Comment by adonyssantos** [comment]
> @adonyssantos The horizontal space that you mention, corresponds to the scroll

Thanks!!
