### ISSUE TITLE
Create title components (h1-h6)

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/palm-treee-css#75]
Add styles to the `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`and `<h6>` tags.

**Comment by ehmenzala** [comment]
```
|-- semantic/
|   |-- src/
|       |-- elements/
|           |-- _headings.scss
|           |-- ...
|-- utilities-class/
|   |-- src/
|       |-- components/
|           |-- _typography.scss
|           |-- ...
```

I was checking this issue and I found that the headings' styles were already defined in the `_typography.scss` partial (Inside `utilities-class` package). This confused me because in the `semantic/` package it is a partial called `_headings.scss`. Where should the headings' styles belong?

**Comment by adonyssantos** [comment]
> ```
> |-- semantic/
> |   |-- src/
> |       |-- elements/
> |           |-- _headings.scss
> |           |-- ...
> |-- utilities-class/
> |   |-- src/
> |       |-- components/
> |           |-- _typography.scss
> |           |-- ...
> ```
> 
> I was checking this issue and I found that the headings' styles were already defined in the `_typography.scss` partial (Inside `utilities-class` package). This confused me because in the `semantic/` package it is a partial called `_headings.scss`. Where should the headings' styles belong?

@ehmenzala this feature should be in the `_headings.scss` file in the **@palm-tree-css/semantic** module

**Comment by adonyssantos** [comment]
This will be worked on #92
