### ISSUE TITLE
Create paragraph component

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/palm-treee-css#76]
Add styles to the `<p>` tag.

**Comment by AcxelAmbrosi** [comment]
Where can I see the design that is required?

**Comment by adonyssantos** [comment]
> Where can I see the design that is required?

We are creating a design on Figma and talking about it on the @Gentleman-Programming's Discord. But for now, the `<p>` will have a font-size of 16px;

**Comment by adonyssantos** [comment]
This will be worked on #92
